# MAVROS Configuration for KAERTEI 2025 FAIO Drone
# Pixhawk 2.1 Cube Orange with ArduPilot

# Connection settings
fcu_url: "serial:///dev/ttyUSB0:57600"  # Adjust port and baudrate as needed
gcs_url: "udp://@127.0.0.1:14550"      # For QGroundControl connection

# System settings
target_system_id: 1
target_component_id: 1
fcu_protocol: v2.0

# Plugin settings
plugin_blacklist:
  - safety_area
  - 3dr_radio
  - actuator_control
  - command
  - dummy
  - ftp
  - global_position
  - imu_pub
  - local_position
  - manual_control
  - param
  - rc_io
  - waypoint

plugin_whitelist:
  - sys_status
  - sys_time
  - heartbeat
  - gps
  - setpoint_position
  - setpoint_velocity
  - command
  - local_position
  - global_position

# GPS settings
gps:
  time_ref_source: gps
  use_gps_time: true

# Local position settings
local_position:
  frame_id: "map"
  tf_send: true
  tf_frame_id: "map"
  tf_child_frame_id: "base_link"

# System time settings
time:
  time_ref_source: gps
  timesync_avg_alpha: 0.6
